[DOC] Rewrite documentation to RST format
romm/NotiZ pull request #162
Opened 2018-11-28 12:34 UTC by romm

2018-11-28 16:57 UTC, AzOoDev reviewed
Pour le `we` que j'ai enlevé dans la page d'exemple c'est juste que je trouvais bizarre ...
Soit j'aurais mis `you can` ou rien du tout partout sur le reste de la page ^^

2018-11-28 16:57 UTC, AzOoDev commented on Documentation/04-Notification/Email/Index.rst
> +They can can be configured in the definition at the path:
```suggestion
They can be configured in the definition at the path:
```

2018-11-28 16:57 UTC, AzOoDev commented on Documentation/03-Example/Index.rst
> +notification types is shown, we click on the button to create a new email
```suggestion
notification types is shown, click on the button to create a new email
```

2018-12-06 21:45 UTC, Mopolo requested changes

2018-12-06 21:45 UTC, Mopolo commented on Documentation/04-Notification/Log/Index.rst
> +.. _PSR-3 Log Level: http://www.php-fig.org/psr/psr-3/#psrlogloglevel
The link changed.

```suggestion
.. _PSR-3 Log Level: https://www.php-fig.org/psr/psr-3/#5-psrlogloglevel
```

2018-12-06 21:45 UTC, Mopolo commented on Documentation/04-Notification/Slack/Index.rst
> +Bots can defined in the definition:
```suggestion
Bots can be defined in the definition:
```

2018-12-06 21:45 UTC, Mopolo commented on Documentation/05-Event/ProvidedEvent/02-Scheduler/SchedulerTaskWasExecuted.rst
> +uid          Uid of the task, for instance `123`
```suggestion
uid          Uid of the task, for instance ``123``
```

2018-12-06 21:45 UTC, Mopolo commented on Documentation/05-Event/ProvidedEvent/02-Scheduler/SchedulerTaskWasExecuted.rst
> +title        Title of the task, for instance `Reporting`
```suggestion
title        Title of the task, for instance ``Reporting``
```

2018-12-06 21:45 UTC, Mopolo commented on Documentation/06-Administrator/02-CustomEvent/Index.rst
> +The most common way to send an event is to use TYPO3 signal API. This signal
```suggestion
The most common way to send an event is to use the TYPO3 signal API. This signal
```

2018-12-06 21:45 UTC, Mopolo commented on Documentation/06-Administrator/02-CustomEvent/Index.rst
> +    Hooks may also be used, even if signals should be preferred.
```suggestion
    Hooks may also be used, but signals should be preferred.
```

2018-12-06 21:45 UTC, Mopolo commented on Documentation/06-Administrator/02-CustomEvent/Index.rst
> +    If one need a more specific implementation for an event, the interface
```suggestion
    If one needs a more specific implementation for an event, the interface
```

2018-12-06 21:45 UTC, Mopolo commented on Documentation/06-Administrator/02-CustomEvent/Index.rst
> +Here is an event bound to our previous sent signal:
```suggestion
Here is an event bound to our previously sent signal:
```

2018-12-06 21:45 UTC, Mopolo commented on Documentation/06-Administrator/02-CustomEvent/Index.rst
> +    - In a log, the will be available in the message.
```suggestion
    - In a log, they will be available in the message.
```

2018-12-06 22:02 UTC, AzOoDev requested changes

2018-12-06 22:02 UTC, AzOoDev commented on Documentation/04-Notification/Log/Index.rst
> +Log content
```suggestion
Log configuration
```

2018-12-06 22:02 UTC, AzOoDev commented on Documentation/04-Notification/Slack/Index.rst
> +Bots can defined in the definition:
```suggestion
Bots are defined in the definition:
```

2018-12-06 22:02 UTC, AzOoDev commented on Documentation/04-Notification/Slack/Index.rst
> +webhookUrl  The Slack URL to which the notification is sent to.
```suggestion
webhookUrl  The Slack URL which the notification is sent to.
```

2018-12-06 22:02 UTC, AzOoDev commented on Documentation/05-Event/Index.rst
> +See chapter “:ref:`events-providedEvent`” for a full list of all provided
```suggestion
See chapter “:ref:`events-providedEvent`” for a full list of provided
```

2018-12-06 22:02 UTC, AzOoDev commented on Documentation/06-Administrator/04-SignalsConnection/Index.rst
> +sent. It means that the signal may be sent several times for this very event.
```suggestion
sent. It means that the signal may be sent several times for this event.
```

2018-12-10 19:43 UTC, Mopolo approved these changes

2018-12-10 19:48 UTC, merged