[BUGFIX] Use middleware for event definition registration
romm/NotiZ pull request #213
Opened 2020-04-04 00:01 UTC by romm

With TYPO3 v9.5+ hooks have been deprecated in favor of middleware
usage. Some hooks would event not run like they used to in former
versions.

This commit introduces a new middleware (which is used both in frontend
and backend) to register the event definitions.

2020-04-06 10:39 UTC, Mopolo requested changes

2020-04-06 10:39 UTC, Mopolo commented on Classes/Middleware/EventDefinitionRegistererMiddleware.php
> + * Copyright (C) 2018
The year is not correct :p

```suggestion
 * Copyright (C) 2020
```

2020-04-06 10:39 UTC, Mopolo commented on Configuration/RequestMiddlewares.php
> + * Copyright (C) 2018
```suggestion
 * Copyright (C) 2020
```

2020-04-06 20:12 UTC, romm commented
Oh my god are you kidding me StyleCI?!

2020-04-06 20:14 UTC, romm commented
GOD DAMNIT

2020-04-07 09:18 UTC, Mopolo submitted a review, later dismissed

2020-04-07 23:54 UTC, romm commented
There you go. ಠ_ಠ

2020-04-08 10:28 UTC, Mopolo approved these changes

2020-04-10 01:07 UTC, merged